
hyper_server:
  listener:
    url: https://localhost:8443
    ssl:
      cert: "examples/self_signed_cert.pem"
    max_socket: 20

hyper_client:
  service_name: "hyper_service"
  backends:
    - url: https://localhost:8443
      ssl:
        store:
          path: "examples/"
  min_socket: 2
  max_socket: 20

observability:
  level: DEBUG
  metrics:
    #otlp: # Opentelemetry protocol
    #  endpoint: "http://localhost:4137"
    #  timeout_sec: 3
    #  protocol: Grpc
    prometheus:
      endpoint: "0.0.0.0:9090"
    stdout:
      level: debug
  traces:
    #otlp: # Opentelemetry protocol
    #  endpoint: "http://localhost:4137"
    #  timeout_sec: 3
    #  protocol: Grpc
    stdout:
      level: debug
  logs:
    #otlp: # Opentelemetry protocol
    #  endpoint: "http://localhost:4137"
    #  timeout_sec: 3
    #  protocol: Grpc
    stdout:
      level: debug
